### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Flight1903** [richgieg/runo#5]
for some reason your server keeps going down

**Comment by Flight1903** [comment]
https://www.richgieg.com/runo/

**Comment by richgieg** [comment]
Thanks for reporting that. This happens from time to time. The app uses a temporary "games.lock" file for synchronizing reads/writes to game data files coming from all the clients being served. I think there's a bug in the synchronization code because sometimes the "games.lock" file remains present indefinitely, causing the issue you're seeing. Anyway, I'll look into this soon as well.

**Comment by Flight1903** [comment]
couldn't u just use a permanent games.lock folder instead of creating one every second for syncro?

**Comment by austinhuang0131** [comment]
It's down again

**Comment by richgieg** [comment]
App has been updated to use Google Firestore rather than server's file system. This will prevent the file locking issue.
